Char, Hexa, Base64, ASCII, and Unicode
fluent-check/fluent-check pull request #156
Opened 2021-03-16 13:02 UTC by RuiGuedes

Covers the following points of #45: Char, Hexa, base64, ASCII, and Unicode.

2021-03-16 16:56 UTC, RuiGuedes commented
This PR is almost finished. Currently, the only thing missing is changing the `string()` function to be based on `CharArbitraries` instead of its current state. However, such modification depends on the `MappedArbitrary` `canGenerate()` function, which limitation is addressed on PR #153.

Even though such modification could be made in another PR I see more fit to be done on this one to encapsulate all the logic associated with `strings` and `chars` on this PR. Therefore, this PR is on hold until PR #153 is merged.

2021-03-16 19:11 UTC, RuiGuedes commented
Despite this PR being marked as **draft** I believe that it is almost finished. The only thing missing is a set of tests to test the newly implemented functions. As such @ruippeixotog @arestivo @hugoferreira feel free to start giving me your feedback.

2021-03-18 18:23 UTC, RuiGuedes commented
Depends on #153

2021-03-19 12:25 UTC, RuiGuedes commented on src/arbitraries/index.ts
> +  string(unscaledMin + 3 - ((unscaledMin + 3) % 4), unscaledMax - (unscaledMax % 4), base64())
I agree with and in fact, @hugoferreira has already stated the same. My doubt is if want to make such alterations in another PR or include them in this one. Let me know what you think guys.

2021-03-19 18:54 UTC, ruippeixotog commented on src/arbitraries/index.ts
> +  string(unscaledMin + 3 - ((unscaledMin + 3) % 4), unscaledMax - (unscaledMax % 4), base64())
Given that this PR is introducing these functions, I see no reason why we shouldn't put them in the right place from the start :+1:

2021-03-20 11:09 UTC, RuiGuedes commented on src/arbitraries/index.ts
> +  string(unscaledMin + 3 - ((unscaledMin + 3) % 4), unscaledMax - (unscaledMax % 4), base64())
@ruippeixotog @hugoferreira Already added a new `string.ts` file for encapsulating the logic associated with characters and strings. Do you guys have more suggestions to be made?

2021-03-22 19:09 UTC, hugoferreira requested changes

2021-03-22 19:09 UTC, hugoferreira commented on src/arbitraries/index.ts
> +export {char, hex, base64, ascii, unicode, string,} from './string'
nit: extra `,`

2021-03-22 20:47 UTC, RuiGuedes commented on src/arbitraries/index.ts
> +export {char, hex, base64, ascii, unicode, string,} from './string'
Done!

2021-03-22 20:56 UTC, merged